site_name: OpenCVE Documentation (GL Fork)

dev_addr: 127.0.0.1:8001
repo_name: Gael-Lejeune/opencve-docs
repo_url: https://github.com/Gael-Lejeune/opencve-docs
edit_uri: ""

theme:
  logo: images/logo.png
  favicon: images/favicon.png
  name: 'material'
  palette:
    accent: blue

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - What is this fork ?: 'what-is-this-fork.md'
  - Installation:
    - Manual: 'installation/manual.md'
    - Docker: 'installation/docker.md'
  - How it Works: 'how-it-works.md'
  - Commands: 'commands.md'
  - Admin: 'admin.md'
  - Settings: 'settings.md'
  - API:
    - Introduction: 'api/index.md'
    - /account: 'api/account.md'
    - /cve: 'api/cve.md'
    - /cwe: 'api/cwe.md'
    - /vendors: 'api/vendors.md'
    - /products: 'api/products.md'
    - /reports: 'api/reports.md'
    - /alerts: 'api/alerts.md'
    - /categories: 'api/categories.md'
  - FAQ: 'faq.md'
